services:
  backend:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/app/tracker.db:/app/backend/app/tracker.db  # Persist SQLite file
    environment:
      - DATABASE_URL=sqlite:///./app/tracker.db   # SQLite database URL for FastAPI
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    stdin_open: true
    tty: true

  redis:
      image: redis:alpine
      container_name: redis_cache
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data  # Persist Redis data
      command: redis-server --save 60 1 --loglevel warning  # Save every 60 sec if at least 1 change

volumes:
  redis_data:  # Define the named volume
