services:
  backend:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/app/tracker.db:/app/backend/app/tracker.db  # Persist SQLite file
    environment:
      - DATABASE_URL=sqlite:///./app/tracker.db   # SQLite database URL for FastAPI

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    stdin_open: true
    tty: true
