"""create initial tables

Revision ID: 1ea2b5e7632a
Revises: 
Create Date: 2024-11-16 23:10:30.352106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea2b5e7632a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(), nullable=True),
    sa.Column('traditional', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_simplified'), 'entries', ['simplified'], unique=False)
    op.create_index(op.f('ix_entries_traditional'), 'entries', ['traditional'], unique=False)
    op.create_table('hsk_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsk_levels_id'), 'hsk_levels', ['id'], unique=False)
    op.create_index(op.f('ix_hsk_levels_level'), 'hsk_levels', ['level'], unique=True)
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_text'), 'sentences', ['text'], unique=False)
    op.create_table('wordlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_modified', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordlists_id'), 'wordlists', ['id'], unique=False)
    op.create_index(op.f('ix_wordlists_name'), 'wordlists', ['name'], unique=False)
    op.create_index(op.f('ix_wordlists_time_created'), 'wordlists', ['time_created'], unique=False)
    op.create_index(op.f('ix_wordlists_time_modified'), 'wordlists', ['time_modified'], unique=False)
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_definitions_definition'), 'definitions', ['definition'], unique=False)
    op.create_index(op.f('ix_definitions_entry_id'), 'definitions', ['entry_id'], unique=False)
    op.create_table('pronunciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciations_entry_id'), 'pronunciations', ['entry_id'], unique=False)
    op.create_index(op.f('ix_pronunciations_pinyin'), 'pronunciations', ['pinyin'], unique=False)
    op.create_table('wordlist_entries',
    sa.Column('wordlist_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['wordlist_id'], ['wordlists.id'], ),
    sa.PrimaryKeyConstraint('wordlist_id', 'entry_id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(), nullable=True),
    sa.Column('traditional', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['hsk_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_definition'), 'words', ['definition'], unique=False)
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_pinyin'), 'words', ['pinyin'], unique=False)
    op.create_index(op.f('ix_words_simplified'), 'words', ['simplified'], unique=False)
    op.create_index(op.f('ix_words_traditional'), 'words', ['traditional'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_traditional'), table_name='words')
    op.drop_index(op.f('ix_words_simplified'), table_name='words')
    op.drop_index(op.f('ix_words_pinyin'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_index(op.f('ix_words_definition'), table_name='words')
    op.drop_table('words')
    op.drop_table('wordlist_entries')
    op.drop_index(op.f('ix_pronunciations_pinyin'), table_name='pronunciations')
    op.drop_index(op.f('ix_pronunciations_entry_id'), table_name='pronunciations')
    op.drop_table('pronunciations')
    op.drop_index(op.f('ix_definitions_entry_id'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_definition'), table_name='definitions')
    op.drop_table('definitions')
    op.drop_index(op.f('ix_wordlists_time_modified'), table_name='wordlists')
    op.drop_index(op.f('ix_wordlists_time_created'), table_name='wordlists')
    op.drop_index(op.f('ix_wordlists_name'), table_name='wordlists')
    op.drop_index(op.f('ix_wordlists_id'), table_name='wordlists')
    op.drop_table('wordlists')
    op.drop_index(op.f('ix_sentences_text'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_hsk_levels_level'), table_name='hsk_levels')
    op.drop_index(op.f('ix_hsk_levels_id'), table_name='hsk_levels')
    op.drop_table('hsk_levels')
    op.drop_index(op.f('ix_entries_traditional'), table_name='entries')
    op.drop_index(op.f('ix_entries_simplified'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
